default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jwtest_development

test:
  <<: *default
  database: jwtest_test

production:
  <<: *default
  database: jwtest_production
  username: jwtest
  password: <%= ENV['QUIZ_ME_DATABASE_PASSWORD'] %>
